import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./index.css";
import "./responsive.css";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/lib/Providers";
import { ThemeProvider } from 'next-themes';
import { CustomersProvider } from '@/context/CustomersContext';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZamZam Cold Storage",
  description: "Generated by ZamZam Cold Storage",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <CustomersProvider>
              <Toaster />
              {children}
            </CustomersProvider>
          </Providers>
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}